In [2]:
import glob
import pandas as pd
import datetime
import IPython.display as display

In [3]:
dfs = []
for filename in glob.glob('selectedData/*'):
    df = pd.read_csv(filename)
    df.name = filename.split('/')[-1].split('.')[0]
    df['Date'] =  pd.to_datetime(df['Date'])
    df.sort_index(axis=1, ascending=False)
    dfs.append(df)

In [4]:
for i in range(len(dfs)):
    df = dfs[i]
    dfs[i] = df[(df['Date']>='2016-11-07') & (df['Date']<='2017-11-10')].reset_index(drop=True)
    dfs[i].name = df.name

In [5]:
checkDate = []
for df in dfs:
    checkDate.append(df[(df['Date']>='2016-11-07') & (df['Date']<='2017-11-10')]['Date'].tolist() == dfs[0][(dfs[0]['Date']>='2016-11-07') & (dfs[0]['Date']<='2017-11-10')]['Date'].tolist())
dateChecked = True
for i in checkDate:
    if(not i):
        dateChecked = False
        print("Date does not match for some.")
        break
if dateChecked:
    print("Date checked successfully")

Date checked successfully

In [13]:
def preprocess(df):
    '''
    Values are calculated w.r.t to the previous week. 
    Delta for week 0 is calculated as open price for start of week 0 - week -1
    High for week 0: Highest price from start of week -1 to start of week 1
    Low for week 0: Lowest price from start of week -1 to start of week 0 
    '''
    currentDate = datetime.datetime(2016,11,17)
    endDate = datetime.datetime(2017,11,10)
    df_ = pd.DataFrame(columns=['Date','Open','Delta','FractionalIncrease','High','Low','Positive'])
    while currentDate <= endDate:
        i = []
        tempDate = currentDate
        while(len(i) == 0):
            i = df.index[df.Date == tempDate].values
            tempDate += datetime.timedelta(days=1)
        i = i[0]
        
        prevI = []
        tempDate = currentDate - datetime.timedelta(days=7)
        while(len(prevI) == 0):
            prevI = df.index[df.Date == tempDate].values
            tempDate += datetime.timedelta(days=1)
        prevI = prevI[0]
        
        date = df.iloc[i]['Date']
        open_ = df.iloc[i]['Open']
        delta = df.iloc[i]['Open'] - df.iloc[prevI]['Open']
        fractionalIncrease = delta/df.iloc[prevI]['Open']
        high = max(df.iloc[prevI:i]['High'])
        low = min(df.iloc[prevI:i]['Low'])
        positive = delta >= 0
        df_.loc[len(df_)] = [date,open_,delta,fractionalIncrease,high,low,positive]
        currentDate += datetime.timedelta(days=7)
    return df_
        
preprocess(dfs[0])

         Date    Open  Delta  FractionalIncrease    High     Low Positive
0  2016-11-17  30.798 -1.261           -0.039334  32.550  30.673    False
1  2016-11-25  30.403 -0.395           -0.012826  30.904  29.471    False
2  2016-12-01  31.029  0.626            0.020590  31.140  30.307     True
3  2016-12-08  29.673 -1.356           -0.043701  31.029  29.447    False
4  2016-12-15  31.395  1.722            0.058033  32.039  29.355     True
5  2016-12-22  31.068 -0.327           -0.010416  31.721  31.106    False
6  2016-12-29  31.164  0.096            0.003090  31.481  30.837     True
7  2017-01-05  32.107  0.943            0.030259  32.089  31.087     True
8  2017-01-12  31.298 -0.809           -0.025197  32.424  31.174    False
9  2017-01-19  30.847 -0.451           -0.014410  31.539  30.577    False
10 2017-01-26  30.211 -0.636           -0.020618  30.904  29.730    False
11 2017-02-02  30.587  0.376            0.012446  30.801  29.763     True
12 2017-02-09  31.355  0.768            0.025109  31.443  30.442     True
13 2017-02-16  32.512  1.157            0.036900  32.638  31.326     True
14 2017-02-23  32.755  0.243            0.007474  32.939  32.289     True
15 2017-03-02  33.494  0.739            0.022561  33.561  32.638     True
16 2017-03-09  32.929 -0.565           -0.016869  33.775  32.775    False
17 2017-03-16  33.601  0.672            0.020408  33.727  32.832     True
18 2017-03-23  33.357 -0.244           -0.007262  33.658  33.036    False
19 2017-03-30  33.230 -0.127           -0.003807  33.591  32.794    False
20 2017-04-06  33.183 -0.047           -0.001414  33.551  33.096    False
21 2017-04-13  32.929 -0.254           -0.007655  33.387  32.765    False
22 2017-04-20  32.687 -0.242           -0.007349  33.096  32.609    False
23 2017-04-27  33.007  0.320            0.009790  33.076  32.531     True
24 2017-05-04  32.502 -0.505           -0.015300  33.066  31.958    False
25 2017-05-11  32.375 -0.127           -0.003907  32.677  32.287    False
26 2017-05-18  31.600 -0.775           -0.023938  32.561  31.609    False
27 2017-05-25  31.463 -0.137           -0.004335  31.895  31.374    False
28 2017-06-01  32.061  0.598            0.019006  32.179  31.374     True
29 2017-06-08  31.463 -0.598           -0.018652  32.267  31.305    False
30 2017-06-15  32.011  0.548            0.017417  32.503  31.080     True
31 2017-06-22  33.318  1.307            0.040830  33.459  31.953     True
32 2017-06-29  33.170 -0.148           -0.004442  33.837  33.022    False
33 2017-07-06  33.013 -0.157           -0.004733  33.336  32.748    False
34 2017-07-13  32.601 -0.412           -0.012480  33.042  32.405    False
35 2017-07-20  32.846  0.245            0.007515  33.062  32.375     True
36 2017-07-27  32.179 -0.667           -0.020307  33.072  32.213    False
37 2017-08-03  32.652  0.473            0.014699  32.768  32.081     True
38 2017-08-10  33.068  0.416            0.012740  33.692  32.562     True
39 2017-08-17  32.989 -0.079           -0.002389  33.261  32.840    False
40 2017-08-24  33.068  0.079            0.002395  33.147  32.027     True
41 2017-08-31  33.197  0.129            0.003901  33.316  32.870     True
42 2017-09-07  33.732  0.535            0.016116  33.856  33.177     True
43 2017-09-14  34.733  1.001            0.029675  35.426  33.494     True
44 2017-09-21  35.733  1.000            0.028791  35.882  34.693     True
45 2017-09-28  34.951 -0.782           -0.021885  35.862  34.876    False
46 2017-10-05  35.555  0.604            0.017281  35.912  34.901     True
47 2017-10-12  36.150  0.595            0.016735  36.150  35.426     True
48 2017-10-19  35.565 -0.585           -0.016183  36.150  35.426    False
49 2017-10-26  35.763  0.198            0.005567  36.447  35.515     True
50 2017-11-02  34.951 -0.812           -0.022705  35.887  33.796    False
51 2017-11-09  35.080  0.129            0.003691  35.288  34.713     True