In [1]:
import pandas as pd
import numpy as np

In [63]:
df = pd.read_csv("../mined/Combined/WellsFargoProcessed.csv", index_col=False)
df = df.drop(df.columns[0],axis=1)

In [64]:
df["Year"] = df["StartDate"]%10000
df["Date"] = (df["StartDate"]%1000000/10000).astype(int)
df["Month"] = (df["StartDate"]/1000000).astype(int)

In [65]:
df = df.sort_values(by=["Year", "Month", "Date"])

In [66]:
df

,Author,EndDate,Site,StartDate,Text,Title,sv_score,Year,Date,Month
1497,NaN,12082016,Reuters,12012016,The amendment also calls for the chairman and ...,\r\n Wells Fargo amends bylaws ...,0.9512,2016,1,12
1498,NaN,12082016,Reuters,12012016,"CANNON BALL/WEST FARGO, N.D. (Reuters) - U.S. ...",\r\n U.S. veterans arrive at pi...,0.9264,2016,1,12
1499,NaN,12082016,Reuters,12012016,"CANNON BALL, N.D. (Reuters) - U.S. military ve...",\r\n U.S. veterans build barrac...,-0.8043,2016,1,12
1500,NaN,12082016,Reuters,12012016,"NEW YORK, Dec 5 (Reuters) - Banks predict Coll...",\r\n LPC: Banks' 2017 CLO forec...,0.9451,2016,1,12
1501,NaN,12082016,Reuters,12012016,The company’s application is the first to seek...,\r\n Philip Morris seeks U.S. a...,0.9655,2016,1,12
1502,NaN,12082016,Reuters,12012016,NEW YORK (Reuters) - Rhode Island-based Citize...,\r\n Citizens Bank signs SigFig...,0.9657,2016,1,12
1503,NaN,12082016,Reuters,12012016,"NEW YORK (Reuters) - BlackRock Inc, the world’...",\r\n BlackRock to move to New Y...,0.9423,2016,1,12
1504,NaN,12082016,Reuters,12012016,(The Dec 6 story is refiled with full company ...,\r\n U.S. corporate bond issuan...,0.9814,2016,1,12
1505,NaN,12082016,Reuters,12012016,(Reuters) - Starbucks Chief Executive Howard S...,\r\n Starbucks' CEO transition ...,0.9922,2016,1,12
1506,Richard Saintvilus,12082016,Investopedia,12012016,Find the best broker for your trading or inves...,Bank of America Not Afraid of 'Cross-Selling' ...,-0.4033,2016,1,12
1507,Mark Kolakowski,12082016,Investopedia,12012016,Find the best broker for your trading or inves...,Trump’s Tax Cut May Cause Huge Bank Writedowns...,0.9835,2016,1,12
1508,Richard Saintvilus,12082016,Investopedia,12012016,Find the best broker for your trading or inves...,Bank Stocks Have Become Overbought: Analyst (K...,0.9862,2016,1,12
1509,Michael Foster,12082016,Investopedia,12012016,Find the best broker for your trading or inves...,"Unstoppable Banks in Trump’s America (MS, GS) ...",0.9589,2016,1,12
1510,"Scott Hanson, co-CEO of Hanson McClain Advisors",12082016,CNBC,12012016,Is your employer profiting from the money you'...,Is your employer using your 401(k) to rip you ...,0.9982,2016,1,12
1511,Giovanny Moreano,12082016,CNBC,12012016,"David Blitzer, chairman of the Index Committee...",S&P's index guru David Blitzer on passive inve...,0.9693,2016,1,12
1512,Patti Domm,12082016,CNBC,12012016,"At least initially, Italy could call the shots...",Why Italy is calling the shots for markets nex...,0.9846,2016,1,12
1513,Jacob Pramuk,12082016,CNBC,12012016,Donald Trump sold all of his stock holdings in...,Trump sold all of his stock holdings this summ...,0.8555,2016,1,12
1514,"Frank Talbot, head of investment research, Cit...",12082016,CNBC,12012016,"Of the 15,000 global portfolio managers tracke...",Ranking America's top 20 female portfolio mana...,0.9982,2016,1,12
1515,Patti Domm,12082016,CNBC,12012016,"There's a fire sale in the bond market, and th...",What's causing the fire sale in the bond market,0.8612,2016,1,12
1516,,12082016,CNBC,12012016,Apple Watch sales appear to have rebounded for...,"Apple latest news: Discounts, advertising spur...",0.9883,2016,1,12
1517,,12082016,CNBC,12012016,"Karen Firestone is Chairman, CEO, and co-found...",Karen Firestone,0.9924,2016,1,12
1518,John Maxfield,12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,"\r\n \r\n By This Measure, Bank of Ame...",0.9891,2016,1,12
1519,Eric Volkman,12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n What Investors Need to Know ...,0.9950,2016,1,12
1520,Tonya Garcia,12082016,MarketWatch,12012016,"Published: Dec 2, 2016 11:17 a.m. ET Johnson k...",Why analysts think Kevin Johnson is the right ...,0.9985,2016,1,12
1521,NaN,12152016,Reuters,12082016,The ruling crowns a dismal year for the San Fr...,\r\n Wells Fargo fails 'living ...,-0.2023,2016,8,12
1522,NaN,12152016,Reuters,12082016,(Reuters) - The top U.S. securities regulator ...,\r\n SEC asks Wells Fargo to ex...,0.9645,2016,8,12
1523,NaN,12152016,Reuters,12082016,Wells Fargo has been hit with a lawsuit accusi...,\r\n Lawsuit says Wells Fargo a...,-0.5719,2016,8,12
1524,NaN,12152016,Reuters,12082016,"NEW YORK, Dec 9 (IFR) - US investment-grade bo...",\r\n US IG breaks records for s...,0.9836,2016,8,12
1525,NaN,12152016,Reuters,12082016,(Reuters) - American Express Co said on Monday...,\r\n AmEx to increase family be...,0.9042,2016,8,12
1526,NaN,12152016,Reuters,12082016,(Reuters) - (Story corrects valuation figure i...,\r\n Annuity provider Athene's ...,-0.3400,2016,8,12
...,...,...,...,...,...,...,...,...,...,...
1472,Thomas Franck,12212017,CNBC,12142017,Callaway Golf's innovative product portfolio i...,JPMorgan initiates Callaway Golf at overweight...,0.9761,2017,14,12
1473,Travis Hoium,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Better Stock: Verizon Commun...,0.9872,2017,14,12
1474,Adam Levy,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Why Enterprise Customers Are...,0.9953,2017,14,12
1475,Daniel B. Kline,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Is Frontier Communications C...,-0.9352,2017,14,12
1476,"Timothy Green, Leo Sun, and Steve Symington",12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 High-Yield Tech Stocks -- ...,0.9977,2017,14,12
1477,"Matthew Frankel, CFP, Sean O'Reilly, and Reube...",12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Dividend Stocks That Pay Y...,0.9713,2017,14,12
1478,Brian Feroldi,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 10 Highest-Yielding Dividend...,0.9956,2017,14,12
1479,Adam Levy,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Sprint Is Planning to Increa...,0.9902,2017,14,12
1480,the Motley Fool Staff,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n How Much Is the NFL Really W...,0.5209,2017,14,12
1481,Travis Hoium,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Wearables Stocks to Buy fo...,0.9949,2017,14,12
1482,Matthew Cochrane,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Time to Get Greedy With Skyw...,0.9973,2017,14,12
1483,Jeff Reeves,12212017,MarketWatch,12142017,"Published: Dec 15, 2017 12:08 p.m. ET Two FAAN...","Three stock winners, three losers in net neutr...",0.9979,2017,14,12
37,NaN,12282017,Reuters,12212017,The decision comes at a time when the third la...,\r\n Wells Fargo launches Stake...,-0.5719,2017,21,12
38,NaN,12282017,Reuters,12212017,WASHINGTON (Reuters) - U.S. President Donald T...,"\r\n Trump signs tax, governmen...",0.8879,2017,21,12
39,NaN,12282017,Reuters,12212017,WASHINGTON (Reuters) - U.S. consumer spending ...,"\r\n Strong U.S. consumer, busi...",0.9953,2017,21,12
40,NaN,12282017,Reuters,12212017,路透华盛顿12月22日 - 美国总统特朗普周五签署了规模达1.5万亿(兆)美元的税改议案，敲...,\r\n 美国总统特朗普签署税改与政府拨款议案 使之成为法律 ...,0.0000,2017,21,12
41,NaN,12282017,Reuters,12212017,路透华盛顿12月22日 - 周五公布的数据显示，11月份美国消费者支出加速上升，主要资本财订...,\r\n 综述：美国11月消费者与企业支出强劲 显示经济成长稳...,0.2500,2017,21,12
1484,NaN,12282017,Reuters,12212017,SAN FRANCISCO (Reuters) - Investors saddled in...,\r\n This year's lumps of coal ...,0.4878,2017,21,12
1485,NaN,12282017,Reuters,12212017,路透旧金山12月22日 - 2017年有些投资者被Under Armour、通用电气等表现糟...,\r\n 美股一周展望：逆向入手衰股 今年的煤块明年可能变成钻...,0.0000,2017,21,12
1486,Mark Kolakowski,12282017,Investopedia,12212017,Find the best broker for your trading or inves...,12 Stocks With Rich Dividends as Market Cools ...,0.9944,2017,21,12
1487,Fred Imbert,12282017,CNBC,12212017,It may be too early to tell if a tax bill that...,Trump says tax bill is 'the rage' in corporate...,0.9768,2017,21,12
1488,Jake Novak,12282017,CNBC,12212017,STOCKS/ECONOMY -Stock futures are higher after...,Morning Top 10,0.6249,2017,21,12
1489,Daniel B. Kline,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Here's Where Things Went Wro...,0.9571,2017,21,12
1490,Daniel B. Kline,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Is Frontier Communications C...,-0.9352,2017,21,12
1491,"Jamal Carnette, CFA",12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 2 Stocks to Profit From the ...,0.9914,2017,21,12
1492,Matthew Cochrane,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Why 2017 Was a Year to Remem...,0.9978,2017,21,12
1493,Matthew Cochrane,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,"\r\n \r\n Why Skyworks Solutions, Inc....",0.9994,2017,21,12
1494,Chris Neiger,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 15 Tech Trends to Watch in 2...,0.9997,2017,21,12
1495,Rich Duprey,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n Is Sears Mortgaging the Futu...,0.9981,2017,21,12
1496,Alessandra Malito,12282017,MarketWatch,12212017,"Published: Dec 21, 2017 2:17 p.m. ET Amazon, V...","With Facebook under fire, 5 ways to battle age...",0.9933,2017,21,12

In [67]:
df2 = pd.read_csv("../processedSelected/wfc.csv", index_col = False)

In [68]:
df2["StockScore"] = (df2["Delta"]/df2["Open"])/0.2

In [69]:
df2["reuter_score"] = 0
df2["reuter_credibility"] = 0
df2["reuter_cumu"] = 0
df2['fool_score'] = 0
df2['fool_credibility'] = 0
df2["fool_cumu"] = 0
df2["invest_score"] = 0
df2["invest_credibility"] = 0
df2["invest_cumu"] = 0
df2["cnbc_score"] = 0
df2["cnbc_credibility"] = 0
df2["cnbc_cumu"] = 0
df2["market_score"] = 0
df2["market_credibility"] = 0
df2["market_cumu"] = 0

In [70]:
df2

,Date,Open,Delta,FractionalIncrease,High,Low,Positive,StockScore,reuter_score,reuter_credibility,reuter_cumu,fool_score,fool_credibility,fool_cumu,invest_score,invest_credibility,invest_cumu,cnbc_score,cnbc_credibility,cnbc_cumu,market_score,market_credibility,market_cumu
0,2016-11-17,49.972,2.391,0.050251,52.569,47.445,True,0.239234,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2016-11-25,50.955,0.983,0.019671,51.519,49.555,True,0.096458,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2016-12-01,51.665,0.710,0.013934,51.694,49.972,True,0.068712,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2016-12-08,55.711,4.046,0.078312,55.711,51.598,True,0.363124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2016-12-15,53.649,-2.062,-0.037012,56.420,52.541,False,-0.192175,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,2016-12-22,54.222,0.573,0.010681,54.766,53.143,True,0.052838,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,2016-12-29,53.668,-0.554,-0.010217,54.554,53.746,False,-0.051614,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,2017-01-05,53.960,0.292,0.005441,54.796,52.977,True,0.027057,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,2017-01-12,53.143,-0.817,-0.015141,54.281,52.239,False,-0.076868,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,2017-01-19,52.744,-0.399,-0.007508,54.650,51.870,False,-0.037824,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,2017-01-26,55.048,2.304,0.043683,55.264,52.375,True,0.209272,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,2017-02-02,54.400,-0.648,-0.011772,55.873,54.212,False,-0.059559,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,2017-02-09,54.806,0.406,0.007463,56.206,54.009,True,0.037040,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,2017-02-16,57.136,2.330,0.042514,57.767,54.502,True,0.203899,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,2017-02-23,57.205,0.069,0.001208,57.401,56.246,True,0.006031,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,2017-03-02,58.526,1.321,0.023092,58.732,56.119,True,0.112856,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,2017-03-09,57.224,-1.302,-0.022247,58.536,56.799,False,-0.113763,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,2017-03-16,57.625,0.401,0.007008,58.066,56.979,True,0.034794,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,2017-03-23,54.071,-3.554,-0.061675,58.165,53.700,False,-0.328642,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,2017-03-30,54.512,0.441,0.008156,55.070,53.103,True,0.040450,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,2017-04-06,53.797,-0.715,-0.013116,55.247,53.641,False,-0.066454,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,2017-04-13,50.714,-3.083,-0.057308,54.482,51.937,False,-0.303959,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,2017-04-20,51.614,0.900,0.017747,52.026,50.180,True,0.087186,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,2017-04-27,53.396,1.782,0.034526,53.932,51.105,True,0.166866,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,2017-05-04,54.490,1.094,0.020488,54.116,52.603,True,0.100385,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,2017-05-11,53.515,-0.975,-0.017893,54.816,53.594,False,-0.091096,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,2017-05-18,51.573,-1.942,-0.036289,53.653,50.922,False,-0.188277,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,2017-05-25,52.499,0.926,0.017955,52.854,51.217,True,0.088192,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,2017-06-01,50.803,-1.696,-0.032305,52.499,50.113,False,-0.166919,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,2017-06-08,51.267,0.464,0.009133,51.573,50.340,True,0.045253,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,2017-06-15,53.278,2.011,0.039226,53.919,51.149,True,0.188727,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,2017-06-22,52.055,-1.223,-0.022955,53.870,52.055,False,-0.117472,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,2017-06-29,54.866,2.811,0.054001,53.653,51.483,True,0.256170,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,2017-07-06,55.190,0.324,0.005905,55.802,54.382,True,0.029353,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,2017-07-13,54.480,-0.710,-0.012865,55.526,53.830,False,-0.065162,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35,2017-07-20,54.185,-0.295,-0.005415,54.886,53.357,False,-0.027222,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,2017-07-27,54.086,-0.099,-0.001827,54.623,53.278,False,-0.009152,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
37,2017-08-03,53.129,-0.957,-0.017694,54.185,52.430,False,-0.090064,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,2017-08-10,52.027,-1.102,-0.020742,53.327,51.550,False,-0.105907,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,2017-08-17,52.106,0.079,0.001518,52.988,51.381,True,0.007581,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,2017-08-24,51.828,-0.278,-0.005335,52.268,51.024,False,-0.026819,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
41,2017-08-31,50.646,-1.182,-0.022806,52.205,50.775,False,-0.116692,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,2017-09-07,49.594,-1.052,-0.020772,51.133,49.216,False,-0.106061,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
43,2017-09-14,51.182,1.588,0.032020,51.371,48.928,True,0.155133,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44,2017-09-21,53.178,1.996,0.038998,53.738,50.726,True,0.187672,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
45,2017-09-28,53.913,0.735,0.013822,54.152,53.149,True,0.068165,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
46,2017-10-05,54.618,0.705,0.013077,55.234,53.367,True,0.064539,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
47,2017-10-12,55.304,0.686,0.012560,55.383,54.400,True,0.062021,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
48,2017-10-19,52.742,-2.562,-0.046326,55.323,52.473,False,-0.242880,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
49,2017-10-26,55.065,2.323,0.044045,55.194,52.632,True,0.210933,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
50,2017-11-02,55.800,0.735,0.013348,56.446,54.747,True,0.065860,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
51,2017-11-09,53.900,-1.900,-0.034050,56.520,54.050,False,-0.176252,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [82]:
for index, row in df2.iterrows():
    year = int(row["Date"].split("-")[0])
    month = int(row["Date"].split("-")[1])
    date = int(row["Date"].split("-")[2])
    reuter_sentiment_score = 0
    reuter_sentiment_count = 0
    fool_sentiment_score = 0
    fool_sentiment_count = 0
    invest_sentiment_score = 0
    invest_sentiment_count = 0
    cnbc_sentiment_score = 0
    cnbc_sentiment_count = 0
    market_sentiment_score = 0
    market_sentiment_count = 0
    reading_frame = df.loc[(df["Year"] == year) & (df["Month"] == month) & (df["Date"] == date)]
    if not reading_frame.empty:
        for reading_index, reading_row in reading_frame.iterrows():
            if reading_row["Site"] == "Reuters":
                reuter_sentiment_score += reading_row["sv_score"]
                reuter_sentiment_count += 1
            elif reading_row["Site"] == "Investopedia":
                invest_sentiment_score += reading_row["sv_score"]
                invest_sentiment_count += 1
            elif reading_row['Site'] == "CNBC":
                cnbc_sentiment_score += reading_row["sv_score"]
                cnbc_sentiment_count += 1
            elif reading_row['Site'] == "Fool":
                fool_sentiment_score += reading_row['sv_score']
                fool_sentiment_count += 1
            elif reading_row['Site'] == 'MarketWatch':
                market_sentiment_score += reading_row["sv_score"]
                market_sentiment_count += 1
    if reuter_sentiment_count > 0:
        df2.loc[index,"reuter_score"] = reuter_sentiment_score/reuter_sentiment_count
        df2.loc[index,"reuter_credibility"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2
        if index == 0:
            df2.loc[index,"reuter_cumu"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2
        else:
            if not pd.isna(df2.loc[index-1, "reuter_cumu"]):
                df2.loc[index, "reuter_cumu"] = (df2.loc[index, "reuter_credibility"]+df2.loc[index-1, "reuter_cumu"])/2
            else:
                df2.loc[index, "reuter_cumu"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2            
    else:
        df2.loc[index,"reuter_score"] = None
        df2.loc[index,"reuter_credibility"] = None
        if index == 0:
            df2.loc[index, "reuter_cumu"] = None
        else:
            if not pd.isna(df2.loc[index-1, "reuter_cumu"]):
                df2.loc[index, "reuter_cumu"] = df2.loc[index-1, "reuter_cumu"]
    if fool_sentiment_count > 0:
        df2.loc[index,'fool_score'] = fool_sentiment_score/fool_sentiment_count
    else:
        df2.loc[index,'fool_score'] = None
    if invest_sentiment_count > 0:
        df2.loc[index,"invest_score"] = invest_sentiment_score/invest_sentiment_count
    else:
        df2.loc[index,"invest_score"] = None
    if cnbc_sentiment_count > 0:
        df2.loc[index,"cnbc_score"] = cnbc_sentiment_score/cnbc_sentiment_count
    else:
         df2.loc[index,"cnbc_score"] = None
    if market_sentiment_count > 0:
        df2.loc[index,"market_score"] = market_sentiment_score/market_sentiment_count
    else:
        df2.loc[index,"market_score"] = None

In [83]:
pd.set_option('display.max_columns', 100)
df2

,Date,Open,Delta,FractionalIncrease,High,Low,Positive,StockScore,reuter_score,reuter_credibility,reuter_cumu,fool_score,fool_credibility,fool_cumu,invest_score,invest_credibility,invest_cumu,cnbc_score,cnbc_credibility,cnbc_cumu,market_score,market_credibility,market_cumu
0,2016-11-17,49.972,2.391,0.050251,52.569,47.445,True,0.239234,NaN,NaN,NaN,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
1,2016-11-25,50.955,0.983,0.019671,51.519,49.555,True,0.096458,NaN,NaN,NaN,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
2,2016-12-01,51.665,0.710,0.013934,51.694,49.972,True,0.068712,0.762833,0.652939,0.652939,0.992050,0,0,0.631325,0,0,0.955963,0,0,0.998500,0,0
3,2016-12-08,55.711,4.046,0.078312,55.711,51.598,True,0.363124,0.521760,0.920682,0.786811,0.990760,0,0,0.517200,0,0,0.814360,0,0,0.979750,0,0
4,2016-12-15,53.649,-2.062,-0.037012,56.420,52.541,False,-0.192175,0.494786,0.656520,0.721665,0.818171,0,0,0.977200,0,0,0.729400,0,0,0.999500,0,0
5,2016-12-22,54.222,0.573,0.010681,54.766,53.143,True,0.052838,0.503575,0.774632,0.748148,0.991330,0,0,0.956700,0,0,0.653917,0,0,0.999050,0,0
6,2016-12-29,53.668,-0.554,-0.010217,54.554,53.746,False,-0.051614,0.751700,0.598343,0.673246,0.987383,0,0,0.987900,0,0,0.959217,0,0,0.995933,0,0
7,2017-01-05,53.960,0.292,0.005441,54.796,52.977,True,0.027057,0.542740,0.742159,0.707702,0.989320,0,0,0.969800,0,0,0.358570,0,0,0.661100,0,0
8,2017-01-12,53.143,-0.817,-0.015141,54.281,52.239,False,-0.076868,0.788010,0.567561,0.637632,0.996275,0,0,0.989400,0,0,0.514390,0,0,NaN,0,0
9,2017-01-19,52.744,-0.399,-0.007508,54.650,51.870,False,-0.037824,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
10,2017-01-26,55.048,2.304,0.043683,55.264,52.375,True,0.209272,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
11,2017-02-02,54.400,-0.648,-0.011772,55.873,54.212,False,-0.059559,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
12,2017-02-09,54.806,0.406,0.007463,56.206,54.009,True,0.037040,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
13,2017-02-16,57.136,2.330,0.042514,57.767,54.502,True,0.203899,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
14,2017-02-23,57.205,0.069,0.001208,57.401,56.246,True,0.006031,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
15,2017-03-02,58.526,1.321,0.023092,58.732,56.119,True,0.112856,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
16,2017-03-09,57.224,-1.302,-0.022247,58.536,56.799,False,-0.113763,NaN,NaN,0.637632,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
17,2017-03-16,57.625,0.401,0.007008,58.066,56.979,True,0.034794,NaN,NaN,0.637632,0.708067,0,0,NaN,0,0,NaN,0,0,0.906100,0,0
18,2017-03-23,54.071,-3.554,-0.061675,58.165,53.700,False,-0.328642,0.415100,0.628129,0.632880,0.993000,0,0,0.946900,0,0,0.664030,0,0,0.974717,0,0
19,2017-03-30,54.512,0.441,0.008156,55.070,53.103,True,0.040450,0.722518,0.658966,0.645923,0.997150,0,0,0.994800,0,0,0.915712,0,0,0.412471,0,0
20,2017-04-06,53.797,-0.715,-0.013116,55.247,53.641,False,-0.066454,0.573773,0.679887,0.662905,0.992800,0,0,0.959700,0,0,0.473070,0,0,0.706571,0,0
21,2017-04-13,50.714,-3.083,-0.057308,54.482,51.937,False,-0.303959,0.909411,0.393315,0.528110,0.994950,0,0,0.958620,0,0,0.917580,0,0,0.773857,0,0
22,2017-04-20,51.614,0.900,0.017747,52.026,50.180,True,0.087186,0.434525,0.826330,0.677220,0.797960,0,0,0.967700,0,0,0.351137,0,0,0.992550,0,0
23,2017-04-27,53.396,1.782,0.034526,53.932,51.105,True,0.166866,0.402600,0.882133,0.779677,0.967950,0,0,0.951233,0,0,0.592820,0,0,0.988900,0,0
24,2017-05-04,54.490,1.094,0.020488,54.116,52.603,True,0.100385,0.465590,0.817398,0.798537,0.726225,0,0,0.578900,0,0,0.304210,0,0,0.950314,0,0
25,2017-05-11,53.515,-0.975,-0.017893,54.816,53.594,False,-0.091096,0.739662,0.584621,0.691579,0.961391,0,0,0.985500,0,0,0.391800,0,0,0.996600,0,0
26,2017-05-18,51.573,-1.942,-0.036289,53.653,50.922,False,-0.188277,0.542289,0.634717,0.663148,0.968900,0,0,0.985000,0,0,0.850471,0,0,0.996450,0,0
27,2017-05-25,52.499,0.926,0.017955,52.854,51.217,True,0.088192,0.790814,0.648689,0.655918,0.998800,0,0,0.995000,0,0,0.721750,0,0,0.755900,0,0
28,2017-06-01,50.803,-1.696,-0.032305,52.499,50.113,False,-0.166919,0.276720,0.778180,0.717049,0.994075,0,0,0.989200,0,0,0.868214,0,0,0.994700,0,0
29,2017-06-08,51.267,0.464,0.009133,51.573,50.340,True,0.045253,0.532333,0.756460,0.736755,0.726257,0,0,0.993750,0,0,0.644660,0,0,0.960400,0,0
30,2017-06-15,53.278,2.011,0.039226,53.919,51.149,True,0.188727,0.473390,0.857669,0.797212,0.821270,0,0,0.983600,0,0,0.052080,0,0,0.650525,0,0
31,2017-06-22,52.055,-1.223,-0.022955,53.870,52.055,False,-0.117472,NaN,NaN,0.797212,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
32,2017-06-29,54.866,2.811,0.054001,53.653,51.483,True,0.256170,NaN,NaN,0.797212,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
33,2017-07-06,55.190,0.324,0.005905,55.802,54.382,True,0.029353,NaN,NaN,0.797212,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
34,2017-07-13,54.480,-0.710,-0.012865,55.526,53.830,False,-0.065162,NaN,NaN,0.797212,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
35,2017-07-20,54.185,-0.295,-0.005415,54.886,53.357,False,-0.027222,NaN,NaN,0.797212,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
36,2017-07-27,54.086,-0.099,-0.001827,54.623,53.278,False,-0.009152,NaN,NaN,0.797212,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
37,2017-08-03,53.129,-0.957,-0.017694,54.185,52.430,False,-0.090064,0.338009,0.785964,0.791588,0.657530,0,0,0.933200,0,0,0.286690,0,0,0.657414,0,0
38,2017-08-10,52.027,-1.102,-0.020742,53.327,51.550,False,-0.105907,0.860867,0.516613,0.654100,0.821622,0,0,0.991600,0,0,0.356780,0,0,0.807440,0,0
39,2017-08-17,52.106,0.079,0.001518,52.988,51.381,True,0.007581,0.409171,0.799205,0.726653,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
40,2017-08-24,51.828,-0.278,-0.005335,52.268,51.024,False,-0.026819,NaN,NaN,0.726653,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
41,2017-08-31,50.646,-1.182,-0.022806,52.205,50.775,False,-0.116692,NaN,NaN,0.726653,0.971870,0,0,0.877800,0,0,0.243700,0,0,0.206425,0,0
42,2017-09-07,49.594,-1.052,-0.020772,51.133,49.216,False,-0.106061,0.517630,0.688154,0.707403,0.975760,0,0,NaN,0,0,0.475930,0,0,0.677900,0,0
43,2017-09-14,51.182,1.588,0.032020,51.371,48.928,True,0.155133,NaN,NaN,0.707403,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
44,2017-09-21,53.178,1.996,0.038998,53.738,50.726,True,0.187672,0.713086,0.737293,0.722348,0.997500,0,0,0.996400,0,0,0.596500,0,0,0.820775,0,0
45,2017-09-28,53.913,0.735,0.013822,54.152,53.149,True,0.068165,NaN,NaN,0.722348,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
46,2017-10-05,54.618,0.705,0.013077,55.234,53.367,True,0.064539,NaN,NaN,0.722348,NaN,0,0,NaN,0,0,NaN,0,0,NaN,0,0
47,2017-10-12,55.304,0.686,0.012560,55.383,54.400,True,0.062021,0.530033,0.765994,0.744171,0.931364,0,0,0.978600,0,0,0.234690,0,0,0.595473,0,0
48,2017-10-19,52.742,-2.562,-0.046326,55.323,52.473,False,-0.242880,0.067243,0.844938,0.794555,0.974409,0,0,0.987350,0,0,0.794710,0,0,0.580689,0,0
49,2017-10-26,55.065,2.323,0.044045,55.194,52.632,True,0.210933,0.674582,0.768175,0.781365,0.984850,0,0,0.980800,0,0,0.785080,0,0,0.714520,0,0
50,2017-11-02,55.800,0.735,0.013348,56.446,54.747,True,0.065860,0.921340,0.572260,0.676813,0.991840,0,0,0.649700,0,0,0.383300,0,0,0.960700,0,0
51,2017-11-09,53.900,-1.900,-0.034050,56.520,54.050,False,-0.176252,0.719467,0.552141,0.614477,0.974070,0,0,0.745329,0,0,0.864610,0,0,0.939800,0,0

In [23]:
for index, row in df2.iterrows():
    if index == 0: 
        if reuter_score:
            row["reuter_credibility"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2
            row[]
        else:
            row["reuter_credibility"] = 0
        
# df2.to_csv("../scoredSelected/wellsfargoscored.csv", index = False)
# df2.loc[(df2["reuter_count"] > 0) & (df2["fool_count"] > 0) & (df2["invest_count"] > 0) & (df2["cnbc_count"] > 0) & (df2["market_count"] > 0)]

,Date,Open,Delta,FractionalIncrease,High,Low,Positive,StockScore,reuter_score,fool_score,invest_score,cnbc_score,market_score
0,2016-11-17,49.972,2.391,0.050251,52.569,47.445,True,0.239234,NaN,NaN,NaN,NaN,NaN
1,2016-11-25,50.955,0.983,0.019671,51.519,49.555,True,0.096458,NaN,NaN,NaN,NaN,NaN
2,2016-12-01,51.665,0.710,0.013934,51.694,49.972,True,0.068712,0.762833,0.992050,0.631325,0.955963,0.998500
3,2016-12-08,55.711,4.046,0.078312,55.711,51.598,True,0.363124,0.521760,0.990760,0.517200,0.814360,0.979750
4,2016-12-15,53.649,-2.062,-0.037012,56.420,52.541,False,-0.192175,0.494786,0.818171,0.977200,0.729400,0.999500
5,2016-12-22,54.222,0.573,0.010681,54.766,53.143,True,0.052838,0.503575,0.991330,0.956700,0.653917,0.999050
6,2016-12-29,53.668,-0.554,-0.010217,54.554,53.746,False,-0.051614,0.751700,0.987383,0.987900,0.959217,0.995933
7,2017-01-05,53.960,0.292,0.005441,54.796,52.977,True,0.027057,0.542740,0.989320,0.969800,0.358570,0.661100
8,2017-01-12,53.143,-0.817,-0.015141,54.281,52.239,False,-0.076868,0.788010,0.996275,0.989400,0.514390,NaN
9,2017-01-19,52.744,-0.399,-0.007508,54.650,51.870,False,-0.037824,NaN,NaN,NaN,NaN,NaN
10,2017-01-26,55.048,2.304,0.043683,55.264,52.375,True,0.209272,NaN,NaN,NaN,NaN,NaN
11,2017-02-02,54.400,-0.648,-0.011772,55.873,54.212,False,-0.059559,NaN,NaN,NaN,NaN,NaN
12,2017-02-09,54.806,0.406,0.007463,56.206,54.009,True,0.037040,NaN,NaN,NaN,NaN,NaN
13,2017-02-16,57.136,2.330,0.042514,57.767,54.502,True,0.203899,NaN,NaN,NaN,NaN,NaN
14,2017-02-23,57.205,0.069,0.001208,57.401,56.246,True,0.006031,NaN,NaN,NaN,NaN,NaN
15,2017-03-02,58.526,1.321,0.023092,58.732,56.119,True,0.112856,NaN,NaN,NaN,NaN,NaN
16,2017-03-09,57.224,-1.302,-0.022247,58.536,56.799,False,-0.113763,NaN,NaN,NaN,NaN,NaN
17,2017-03-16,57.625,0.401,0.007008,58.066,56.979,True,0.034794,NaN,0.708067,NaN,NaN,0.906100
18,2017-03-23,54.071,-3.554,-0.061675,58.165,53.700,False,-0.328642,0.415100,0.993000,0.946900,0.664030,0.974717
19,2017-03-30,54.512,0.441,0.008156,55.070,53.103,True,0.040450,0.722518,0.997150,0.994800,0.915712,0.412471
20,2017-04-06,53.797,-0.715,-0.013116,55.247,53.641,False,-0.066454,0.573773,0.992800,0.959700,0.473070,0.706571
21,2017-04-13,50.714,-3.083,-0.057308,54.482,51.937,False,-0.303959,0.909411,0.994950,0.958620,0.917580,0.773857
22,2017-04-20,51.614,0.900,0.017747,52.026,50.180,True,0.087186,0.434525,0.797960,0.967700,0.351137,0.992550
23,2017-04-27,53.396,1.782,0.034526,53.932,51.105,True,0.166866,0.402600,0.967950,0.951233,0.592820,0.988900
24,2017-05-04,54.490,1.094,0.020488,54.116,52.603,True,0.100385,0.465590,0.726225,0.578900,0.304210,0.950314
25,2017-05-11,53.515,-0.975,-0.017893,54.816,53.594,False,-0.091096,0.739662,0.961391,0.985500,0.391800,0.996600
26,2017-05-18,51.573,-1.942,-0.036289,53.653,50.922,False,-0.188277,0.542289,0.968900,0.985000,0.850471,0.996450
27,2017-05-25,52.499,0.926,0.017955,52.854,51.217,True,0.088192,0.790814,0.998800,0.995000,0.721750,0.755900
28,2017-06-01,50.803,-1.696,-0.032305,52.499,50.113,False,-0.166919,0.276720,0.994075,0.989200,0.868214,0.994700
29,2017-06-08,51.267,0.464,0.009133,51.573,50.340,True,0.045253,0.532333,0.726257,0.993750,0.644660,0.960400
30,2017-06-15,53.278,2.011,0.039226,53.919,51.149,True,0.188727,0.473390,0.821270,0.983600,0.052080,0.650525
31,2017-06-22,52.055,-1.223,-0.022955,53.870,52.055,False,-0.117472,NaN,NaN,NaN,NaN,NaN
32,2017-06-29,54.866,2.811,0.054001,53.653,51.483,True,0.256170,NaN,NaN,NaN,NaN,NaN
33,2017-07-06,55.190,0.324,0.005905,55.802,54.382,True,0.029353,NaN,NaN,NaN,NaN,NaN
34,2017-07-13,54.480,-0.710,-0.012865,55.526,53.830,False,-0.065162,NaN,NaN,NaN,NaN,NaN
35,2017-07-20,54.185,-0.295,-0.005415,54.886,53.357,False,-0.027222,NaN,NaN,NaN,NaN,NaN
36,2017-07-27,54.086,-0.099,-0.001827,54.623,53.278,False,-0.009152,NaN,NaN,NaN,NaN,NaN
37,2017-08-03,53.129,-0.957,-0.017694,54.185,52.430,False,-0.090064,0.338009,0.657530,0.933200,0.286690,0.657414
38,2017-08-10,52.027,-1.102,-0.020742,53.327,51.550,False,-0.105907,0.860867,0.821622,0.991600,0.356780,0.807440
39,2017-08-17,52.106,0.079,0.001518,52.988,51.381,True,0.007581,0.409171,NaN,NaN,NaN,NaN
40,2017-08-24,51.828,-0.278,-0.005335,52.268,51.024,False,-0.026819,NaN,NaN,NaN,NaN,NaN
41,2017-08-31,50.646,-1.182,-0.022806,52.205,50.775,False,-0.116692,NaN,0.971870,0.877800,0.243700,0.206425
42,2017-09-07,49.594,-1.052,-0.020772,51.133,49.216,False,-0.106061,0.517630,0.975760,NaN,0.475930,0.677900
43,2017-09-14,51.182,1.588,0.032020,51.371,48.928,True,0.155133,NaN,NaN,NaN,NaN,NaN
44,2017-09-21,53.178,1.996,0.038998,53.738,50.726,True,0.187672,0.713086,0.997500,0.996400,0.596500,0.820775
45,2017-09-28,53.913,0.735,0.013822,54.152,53.149,True,0.068165,NaN,NaN,NaN,NaN,NaN
46,2017-10-05,54.618,0.705,0.013077,55.234,53.367,True,0.064539,NaN,NaN,NaN,NaN,NaN
47,2017-10-12,55.304,0.686,0.012560,55.383,54.400,True,0.062021,0.530033,0.931364,0.978600,0.234690,0.595473
48,2017-10-19,52.742,-2.562,-0.046326,55.323,52.473,False,-0.242880,0.067243,0.974409,0.987350,0.794710,0.580689
49,2017-10-26,55.065,2.323,0.044045,55.194,52.632,True,0.210933,0.674582,0.984850,0.980800,0.785080,0.714520
50,2017-11-02,55.800,0.735,0.013348,56.446,54.747,True,0.065860,0.921340,0.991840,0.649700,0.383300,0.960700
51,2017-11-09,53.900,-1.900,-0.034050,56.520,54.050,False,-0.176252,0.719467,0.974070,0.745329,0.864610,0.939800