In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../mined/combine/exxonProcessed.csv", index_col=False)
df = df.drop(df.columns[0],axis=1)

In [3]:
df["Year"] = df["StartDate"]%10000
df["Date"] = (df["StartDate"]%1000000/10000).astype(int)
df["Month"] = (df["StartDate"]/1000000).astype(int)

In [4]:
df = df.sort_values(by=["Year", "Month", "Date"])
df = df.loc[(df["error"] != "Yes")]

In [5]:
df

,Author,EndDate,Site,StartDate,Text,Title,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,sv_score,error,Year,Date,Month
0,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,NaN,NaN,NaN,-0.5719,No,2016,1,12
1,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",NaN,NaN,NaN,-0.5423,No,2016,1,12
2,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Clean Energy Index,NaN,NaN,NaN,0.9451,No,2016,1,12
3,"Benjamin Ra, Ra",12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n The Best Plastic Stocks to B...,NaN,NaN,NaN,0.9970,No,2016,1,12
524,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,NaN,NaN,NaN,-0.5719,No,2016,1,12
525,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",NaN,NaN,NaN,-0.5423,No,2016,1,12
526,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Robotics Index,NaN,NaN,NaN,0.9451,No,2016,1,12
527,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Robotics Index,NaN,NaN,NaN,0.9451,No,2016,1,12
528,"Benjamin Ra, Ra",12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n The Best Plastic Stocks to B...,NaN,NaN,NaN,0.9970,No,2016,1,12
591,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,0.0,NaN,NaN,-0.5719,No,2016,1,12
592,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",1.0,NaN,NaN,-0.5423,No,2016,1,12
593,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Clean Energy Index,2.0,NaN,NaN,0.9451,No,2016,1,12
594,"Benjamin Ra, Ra",12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n The Best Plastic Stocks to B...,4.0,NaN,NaN,0.9970,No,2016,1,12
1115,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,556.0,NaN,NaN,-0.5719,No,2016,1,12
1116,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",557.0,NaN,NaN,-0.5423,No,2016,1,12
1117,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Robotics Index,558.0,NaN,NaN,0.9451,No,2016,1,12
1118,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Robotics Index,559.0,NaN,NaN,0.9451,No,2016,1,12
1119,"Benjamin Ra, Ra",12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n The Best Plastic Stocks to B...,560.0,NaN,NaN,0.9970,No,2016,1,12
1182,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,624.0,0.0,NaN,-0.5719,No,2016,1,12
1183,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",625.0,1.0,NaN,-0.5423,No,2016,1,12
1184,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Clean Energy Index,626.0,2.0,NaN,0.9451,No,2016,1,12
1185,"Benjamin Ra, Ra",12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n The Best Plastic Stocks to B...,627.0,4.0,NaN,0.9970,No,2016,1,12
1706,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,1148.0,556.0,NaN,-0.5719,No,2016,1,12
1707,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",1149.0,557.0,NaN,-0.5423,No,2016,1,12
1708,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Robotics Index,1150.0,558.0,NaN,0.9451,No,2016,1,12
1709,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Robotics Index,1151.0,559.0,NaN,0.9451,No,2016,1,12
1710,"Benjamin Ra, Ra",12082016,Fool,12012016,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n The Best Plastic Stocks to B...,1152.0,560.0,NaN,0.9970,No,2016,1,12
1773,NaN,12082016,Reuters,12012016,(Reuters) - Exxon Mobil has pulled out of half...,\r\n Exxon pulls out of three e...,1215.0,624.0,0.0,-0.5719,No,2016,1,12
1774,NaN,12082016,Reuters,12012016,MEXICO CITY (Reuters) - Mexico awarded a conso...,"\r\n Mexico says Total, ExxonMo...",1216.0,625.0,1.0,-0.5423,No,2016,1,12
1775,,12082016,CNBC,12012016,A look at 50 private companies set to reshape ...,Kensho Clean Energy Index,1217.0,626.0,2.0,0.9451,No,2016,1,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,"Tyler Crowe, Sean O'Reilly, and Reuben Gregg B...",12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Top Oil Stocks to Buy in D...,NaN,NaN,NaN,0.9931,No,2017,14,12
400,Reuben Gregg Brewer,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 2 Top Stocks You Can Buy and...,NaN,NaN,NaN,0.9962,No,2017,14,12
401,Philip van Doorn,12212017,MarketWatch,12142017,"Published: Dec 18, 2017 7:13 a.m. ET Wall Stre...",Analysts expect these energy stocks to rise th...,NaN,NaN,NaN,0.9451,No,2017,14,12
988,NaN,12212017,Investopedia,12142017,Find the best broker for your trading or inves...,Biofuel,426.0,NaN,NaN,0.9923,No,2017,14,12
989,Rebecca Ungarino,12212017,CNBC,12142017,A handful of names in this year's so-called do...,The unlikely ‘dogs of the Dow’ picks that coul...,428.0,NaN,NaN,0.9826,No,2017,14,12
990,"Tyler Crowe, Sean O'Reilly, and Reuben Gregg B...",12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Top Oil Stocks to Buy in D...,429.0,NaN,NaN,0.9931,No,2017,14,12
991,Reuben Gregg Brewer,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 2 Top Stocks You Can Buy and...,430.0,NaN,NaN,0.9962,No,2017,14,12
992,Philip van Doorn,12212017,MarketWatch,12142017,"Published: Dec 18, 2017 7:13 a.m. ET Wall Stre...",Analysts expect these energy stocks to rise th...,431.0,NaN,NaN,0.9451,No,2017,14,12
1579,NaN,12212017,Investopedia,12142017,Find the best broker for your trading or inves...,Biofuel,1021.0,426.0,NaN,0.9923,No,2017,14,12
1580,Rebecca Ungarino,12212017,CNBC,12142017,A handful of names in this year's so-called do...,The unlikely ‘dogs of the Dow’ picks that coul...,1022.0,428.0,NaN,0.9826,No,2017,14,12
1581,"Tyler Crowe, Sean O'Reilly, and Reuben Gregg B...",12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Top Oil Stocks to Buy in D...,1023.0,429.0,NaN,0.9931,No,2017,14,12
1582,Reuben Gregg Brewer,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 2 Top Stocks You Can Buy and...,1024.0,430.0,NaN,0.9962,No,2017,14,12
1583,Philip van Doorn,12212017,MarketWatch,12142017,"Published: Dec 18, 2017 7:13 a.m. ET Wall Stre...",Analysts expect these energy stocks to rise th...,1025.0,431.0,NaN,0.9451,No,2017,14,12
2170,NaN,12212017,Investopedia,12142017,Find the best broker for your trading or inves...,Biofuel,1612.0,1021.0,426.0,0.9923,No,2017,14,12
2171,Rebecca Ungarino,12212017,CNBC,12142017,A handful of names in this year's so-called do...,The unlikely ‘dogs of the Dow’ picks that coul...,1613.0,1022.0,428.0,0.9826,No,2017,14,12
2172,"Tyler Crowe, Sean O'Reilly, and Reuben Gregg B...",12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Top Oil Stocks to Buy in D...,1614.0,1023.0,429.0,0.9931,No,2017,14,12
2173,Reuben Gregg Brewer,12212017,Fool,12142017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 2 Top Stocks You Can Buy and...,1615.0,1024.0,430.0,0.9962,No,2017,14,12
2174,Philip van Doorn,12212017,MarketWatch,12142017,"Published: Dec 18, 2017 7:13 a.m. ET Wall Stre...",Analysts expect these energy stocks to rise th...,1616.0,1025.0,431.0,0.9451,No,2017,14,12
402,NaN,12282017,Reuters,12212017,"NEW YORK/TEPIC, Mexico (Thomson Reuters Founda...",\r\n On the boil: five climate ...,NaN,NaN,NaN,-0.8556,No,2017,21,12
403,Amy Fontinelle,12282017,Investopedia,12212017,Find the best broker for your trading or inves...,"Why do some companies pay a dividend, while ot...",NaN,NaN,NaN,0.9423,No,2017,21,12
405,Sean Williams,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Cryptocurrencies to Consid...,NaN,NaN,NaN,0.9991,No,2017,21,12
993,NaN,12282017,Reuters,12212017,"NEW YORK/TEPIC, Mexico (Thomson Reuters Founda...",\r\n On the boil: five climate ...,432.0,NaN,NaN,-0.8556,No,2017,21,12
994,Amy Fontinelle,12282017,Investopedia,12212017,Find the best broker for your trading or inves...,"Why do some companies pay a dividend, while ot...",433.0,NaN,NaN,0.9423,No,2017,21,12
996,Sean Williams,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Cryptocurrencies to Consid...,436.0,NaN,NaN,0.9991,No,2017,21,12
1584,NaN,12282017,Reuters,12212017,"NEW YORK/TEPIC, Mexico (Thomson Reuters Founda...",\r\n On the boil: five climate ...,1026.0,432.0,NaN,-0.8556,No,2017,21,12
1585,Amy Fontinelle,12282017,Investopedia,12212017,Find the best broker for your trading or inves...,"Why do some companies pay a dividend, while ot...",1027.0,433.0,NaN,0.9423,No,2017,21,12
1587,Sean Williams,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Cryptocurrencies to Consid...,1029.0,436.0,NaN,0.9991,No,2017,21,12
2175,NaN,12282017,Reuters,12212017,"NEW YORK/TEPIC, Mexico (Thomson Reuters Founda...",\r\n On the boil: five climate ...,1617.0,1026.0,432.0,-0.8556,No,2017,21,12
2176,Amy Fontinelle,12282017,Investopedia,12212017,Find the best broker for your trading or inves...,"Why do some companies pay a dividend, while ot...",1618.0,1027.0,433.0,0.9423,No,2017,21,12
2178,Sean Williams,12282017,Fool,12212017,Founded in 1993 by brothers Tom and David Gard...,\r\n \r\n 3 Cryptocurrencies to Consid...,1620.0,1029.0,436.0,0.9991,No,2017,21,12

In [6]:
df2 = pd.read_csv("../processedSelected/xom.csv", index_col = False)

In [7]:
df2["StockScore"] = (df2["Delta"]/df2["Open"])/0.2

In [8]:
df2["reuter_score"] = 0
df2["reuter_credibility"] = 0
df2["reuter_cumu"] = 0
df2['fool_score'] = 0
df2['fool_credibility'] = 0
df2["fool_cumu"] = 0
df2["invest_score"] = 0
df2["invest_credibility"] = 0
df2["invest_cumu"] = 0
df2["cnbc_score"] = 0
df2["cnbc_credibility"] = 0
df2["cnbc_cumu"] = 0
df2["market_score"] = 0
df2["market_credibility"] = 0
df2["market_cumu"] = 0

In [9]:
df2

,Date,Open,Delta,FractionalIncrease,High,Low,Positive,StockScore,reuter_score,reuter_credibility,...,fool_cumu,invest_score,invest_credibility,invest_cumu,cnbc_score,cnbc_credibility,cnbc_cumu,market_score,market_credibility,market_cumu
0,2016-11-17,83.270,0.510,0.006162,84.764,81.232,True,0.030623,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2016-11-25,83.530,0.260,0.003122,84.040,81.720,True,0.015563,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2016-12-01,84.754,1.224,0.014653,84.956,81.959,True,0.072209,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2016-12-08,84.821,0.067,0.000791,85.255,83.424,True,0.003949,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2016-12-15,86.797,1.976,0.023296,89.797,84.436,True,0.113829,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2016-12-22,86.719,-0.078,-0.000899,88.308,86.469,False,-0.004497,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2016-12-29,86.797,0.078,0.000899,87.768,86.719,True,0.004493,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2017-01-05,86.883,0.086,0.000991,87.990,86.459,True,0.004949,0,0,...,0,0,0,0,0,0,0,0,0,0
8,2017-01-12,84.070,-2.813,-0.032377,86.989,82.712,False,-0.167301,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2017-01-19,82.818,-1.252,-0.014892,84.205,82.894,False,-0.075587,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2017-01-26,82.548,-0.270,-0.003260,82.943,81.489,False,-0.016354,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2017-02-02,80.159,-2.389,-0.028941,82.682,79.513,False,-0.149016,0,0,...,0,0,0,0,0,0,0,0,0,0
12,2017-02-09,79.521,-0.638,-0.007959,80.650,78.909,False,-0.040115,0,0,...,0,0,0,0,0,0,0,0,0,0
13,2017-02-16,80.804,1.283,0.016134,80.867,79.389,True,0.079390,0,0,...,0,0,0,0,0,0,0,0,0,0
14,2017-02-23,79.151,-1.653,-0.020457,81.096,78.616,False,-0.104421,0,0,...,0,0,0,0,0,0,0,0,0,0
15,2017-03-02,80.493,1.342,0.016955,81.008,78.510,True,0.083361,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2017-03-09,78.393,-2.100,-0.026089,81.903,78.753,False,-0.133941,0,0,...,0,0,0,0,0,0,0,0,0,0
17,2017-03-16,79.745,1.352,0.017246,80.173,78.072,True,0.084770,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2017-03-23,79.356,-0.389,-0.004878,80.056,79.161,False,-0.024510,0,0,...,0,0,0,0,0,0,0,0,0,0
19,2017-03-30,79.745,0.389,0.004902,79.991,78.540,True,0.024390,0,0,...,0,0,0,0,0,0,0,0,0,0
20,2017-04-06,80.445,0.700,0.008778,81.532,79.064,True,0.043508,0,0,...,0,0,0,0,0,0,0,0,0,0
21,2017-04-13,80.415,-0.030,-0.000373,81.144,80.123,False,-0.001865,0,0,...,0,0,0,0,0,0,0,0,0,0
22,2017-04-20,78.695,-1.720,-0.021389,80.424,78.063,False,-0.109283,0,0,...,0,0,0,0,0,0,0,0,0,0
23,2017-04-27,78.812,0.117,0.001487,80.036,78.228,True,0.007423,0,0,...,0,0,0,0,0,0,0,0,0,0
24,2017-05-04,79.997,1.185,0.015036,80.756,78.685,True,0.074065,0,0,...,0,0,0,0,0,0,0,0,0,0
25,2017-05-11,81.047,1.050,0.013125,80.831,79.133,True,0.064777,0,0,...,0,0,0,0,0,0,0,0,0,0
26,2017-05-18,80.242,-0.805,-0.009933,81.675,80.429,False,-0.050161,0,0,...,0,0,0,0,0,0,0,0,0,0
27,2017-05-25,80.792,0.550,0.006854,81.336,79.899,True,0.034038,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2017-06-01,78.868,-1.924,-0.023814,81.165,78.967,False,-0.121976,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2017-06-08,79.006,0.138,0.001750,79.880,77.779,True,0.008734,0,0,...,0,0,0,0,0,0,0,0,0,0
30,2017-06-15,80.252,1.246,0.015771,82.127,78.986,True,0.077630,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2017-06-22,79.928,-0.324,-0.004037,81.979,79.624,False,-0.020268,0,0,...,0,0,0,0,0,0,0,0,0,0
32,2017-06-29,79.850,-0.078,-0.000976,80.232,79.252,False,-0.004884,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2017-07-06,79.350,-0.500,-0.006262,80.949,78.908,False,-0.031506,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2017-07-13,79.458,0.108,0.001361,79.992,78.319,True,0.006796,0,0,...,0,0,0,0,0,0,0,0,0,0
35,2017-07-20,79.458,0.000,0.000000,79.908,78.770,True,0.000000,0,0,...,0,0,0,0,0,0,0,0,0,0
36,2017-07-27,78.741,-0.717,-0.009024,79.968,78.270,False,-0.045529,0,0,...,0,0,0,0,0,0,0,0,0,0
37,2017-08-03,78.839,0.098,0.001245,79.369,76.808,True,0.006215,0,0,...,0,0,0,0,0,0,0,0,0,0
38,2017-08-10,79.029,0.190,0.002410,79.310,78.289,True,0.012021,0,0,...,0,0,0,0,0,0,0,0,0,0
39,2017-08-17,76.552,-2.477,-0.031343,79.048,76.601,False,-0.161785,0,0,...,0,0,0,0,0,0,0,0,0,0
40,2017-08-24,75.798,-0.754,-0.009850,76.626,75.353,False,-0.049737,0,0,...,0,0,0,0,0,0,0,0,0,0
41,2017-08-31,75.571,-0.227,-0.002995,76.423,75.363,False,-0.015019,0,0,...,0,0,0,0,0,0,0,0,0,0
42,2017-09-07,78.295,2.724,0.036046,78.499,75.353,True,0.173957,0,0,...,0,0,0,0,0,0,0,0,0,0
43,2017-09-14,79.118,0.823,0.010512,79.039,77.889,True,0.052011,0,0,...,0,0,0,0,0,0,0,0,0,0
44,2017-09-21,79.752,0.634,0.008013,79.920,78.821,True,0.039748,0,0,...,0,0,0,0,0,0,0,0,0,0
45,2017-09-28,80.881,1.129,0.014156,80.703,78.939,True,0.069794,0,0,...,0,0,0,0,0,0,0,0,0,0
46,2017-10-05,80.971,0.090,0.001113,81.694,80.500,True,0.005558,0,0,...,0,0,0,0,0,0,0,0,0,0
47,2017-10-12,81.555,0.584,0.007212,81.981,80.609,True,0.035804,0,0,...,0,0,0,0,0,0,0,0,0,0
48,2017-10-19,81.595,0.040,0.000490,82.626,81.417,True,0.002451,0,0,...,0,0,0,0,0,0,0,0,0,0
49,2017-10-26,82.606,1.011,0.012390,83.038,81.575,True,0.061194,0,0,...,0,0,0,0,0,0,0,0,0,0
50,2017-11-02,82.833,0.227,0.002748,83.468,81.258,True,0.013702,0,0,...,0,0,0,0,0,0,0,0,0,0
51,2017-11-09,82.536,-0.297,-0.003586,83.101,82.100,False,-0.017992,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
for index, row in df2.iterrows():
    year = int(row["Date"].split("-")[0])
    month = int(row["Date"].split("-")[1])
    date = int(row["Date"].split("-")[2])
    reuter_sentiment_score = 0
    reuter_sentiment_count = 0
    fool_sentiment_score = 0
    fool_sentiment_count = 0
    invest_sentiment_score = 0
    invest_sentiment_count = 0
    cnbc_sentiment_score = 0
    cnbc_sentiment_count = 0
    market_sentiment_score = 0
    market_sentiment_count = 0
    reading_frame = df.loc[(df["Year"] == year) & (df["Month"] == month) & (df["Date"] == date)]
    if not reading_frame.empty:
        for reading_index, reading_row in reading_frame.iterrows():
            if reading_row["Site"] == "Reuters":
                reuter_sentiment_score += reading_row["sv_score"]
                reuter_sentiment_count += 1
            elif reading_row["Site"] == "Investopedia":
                invest_sentiment_score += reading_row["sv_score"]
                invest_sentiment_count += 1
            elif reading_row['Site'] == "CNBC":
                cnbc_sentiment_score += reading_row["sv_score"]
                cnbc_sentiment_count += 1
            elif reading_row['Site'] == "Fool":
                fool_sentiment_score += reading_row['sv_score']
                fool_sentiment_count += 1
            elif reading_row['Site'] == 'MarketWatch':
                market_sentiment_score += reading_row["sv_score"]
                market_sentiment_count += 1
    if reuter_sentiment_count > 0:
        df2.loc[index,"reuter_score"] = reuter_sentiment_score/reuter_sentiment_count
        df2.loc[index,"reuter_credibility"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2
        if index == 0:
            df2.loc[index,"reuter_cumu"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2
        else:
            if not pd.isna(df2.loc[index-1, "reuter_cumu"]):
                df2.loc[index, "reuter_cumu"] = (df2.loc[index, "reuter_credibility"]+df2.loc[index-1, "reuter_cumu"])/2
            else:
                df2.loc[index, "reuter_cumu"] = 1-(abs(row["reuter_score"] - row["StockScore"]))/2            
    else:
        df2.loc[index,"reuter_score"] = None
        df2.loc[index,"reuter_credibility"] = None
        if index == 0:
            df2.loc[index, "reuter_cumu"] = None
        else:
            if not pd.isna(df2.loc[index-1, "reuter_cumu"]):
                df2.loc[index, "reuter_cumu"] = df2.loc[index-1, "reuter_cumu"]
            else:
                df2.loc[index, "reuter_cumu"] = None
                
    if fool_sentiment_count > 0:
        df2.loc[index,"fool_score"] = fool_sentiment_score/fool_sentiment_count
        df2.loc[index,"fool_credibility"] = 1-(abs(row["fool_score"] - row["StockScore"]))/2
        if index == 0:
            df2.loc[index,"fool_cumu"] = 1-(abs(row["fool_score"] - row["StockScore"]))/2
        else:
            if not pd.isna(df2.loc[index-1, "fool_cumu"]):
                df2.loc[index, "fool_cumu"] = (df2.loc[index, "fool_credibility"]+df2.loc[index-1, "fool_cumu"])/2
            else:
                df2.loc[index, "fool_cumu"] = 1-(abs(row["fool_score"] - row["StockScore"]))/2            
    else:
        df2.loc[index,"fool_score"] = None
        df2.loc[index,"fool_credibility"] = None
        if index == 0:
            df2.loc[index, "fool_cumu"] = None
        else:
            if not pd.isna(df2.loc[index-1, "fool_cumu"]):
                df2.loc[index, "fool_cumu"] = df2.loc[index-1, "fool_cumu"]
            else:
                df2.loc[index, "fool_cumu"] = None
        
    if invest_sentiment_count > 0:
        df2.loc[index,"invest_score"] = invest_sentiment_score/invest_sentiment_count
        df2.loc[index,"invest_credibility"] = 1-(abs(row["invest_score"] - row["StockScore"]))/2
        if index == 0:
            df2.loc[index,"invest_cumu"] = 1-(abs(row["invest_score"] - row["StockScore"]))/2
        else:
            if not pd.isna(df2.loc[index-1, "invest_cumu"]):
                df2.loc[index, "invest_cumu"] = (df2.loc[index, "invest_credibility"]+df2.loc[index-1, "invest_cumu"])/2
            else:
                df2.loc[index, "invest_cumu"] = 1-(abs(row["invest_score"] - row["StockScore"]))/2            
    else:
        df2.loc[index,"invest_score"] = None
        df2.loc[index,"invest_credibility"] = None
        if index == 0:
            df2.loc[index, "invest_cumu"] = None
        else:
            if not pd.isna(df2.loc[index-1, "invest_cumu"]):
                df2.loc[index, "invest_cumu"] = df2.loc[index-1, "invest_cumu"]
            else:
                df2.loc[index, "invest_cumu"] = None

        
    if cnbc_sentiment_count > 0:
        df2.loc[index,"cnbc_score"] = cnbc_sentiment_score/cnbc_sentiment_count
        df2.loc[index,"cnbc_credibility"] = 1-(abs(row["cnbc_score"] - row["StockScore"]))/2
        if index == 0:
            df2.loc[index,"cnbc_cumu"] = 1-(abs(row["cnbc_score"] - row["StockScore"]))/2
        else:
            if not pd.isna(df2.loc[index-1, "cnbc_cumu"]):
                df2.loc[index, "cnbc_cumu"] = (df2.loc[index, "cnbc_credibility"]+df2.loc[index-1, "cnbc_cumu"])/2
            else:
                df2.loc[index, "cnbc_cumu"] = 1-(abs(row["cnbc_score"] - row["StockScore"]))/2            
    else:
        df2.loc[index,"cnbc_score"] = None
        df2.loc[index,"cnbc_credibility"] = None
        if index == 0:
            df2.loc[index, "cnbc_cumu"] = None
        else:
            if not pd.isna(df2.loc[index-1, "cnbc_cumu"]):
                df2.loc[index, "cnbc_cumu"] = df2.loc[index-1, "cnbc_cumu"]
            else:
                df2.loc[index, "cnbc_cumu"] = None

            
    if market_sentiment_count > 0:
        df2.loc[index,"market_score"] = market_sentiment_score/market_sentiment_count
        df2.loc[index,"market_credibility"] = 1-(abs(row["market_score"] - row["StockScore"]))/2
        if index == 0:
            df2.loc[index,"market_cumu"] = 1-(abs(row["market_score"] - row["StockScore"]))/2
        else:
            if not pd.isna(df2.loc[index-1, "market_cumu"]):
                df2.loc[index, "market_cumu"] = (df2.loc[index, "market_credibility"]+df2.loc[index-1, "market_cumu"])/2
            else:
                df2.loc[index, "market_cumu"] = 1-(abs(row["market_score"] - row["StockScore"]))/2            
    else:
        df2.loc[index,"market_score"] = None
        df2.loc[index,"market_credibility"] = None
        if index == 0:
            df2.loc[index, "market_cumu"] = None
        else:
            if not pd.isna(df2.loc[index-1, "market_cumu"]):
                df2.loc[index, "market_cumu"] = df2.loc[index-1, "market_cumu"]
            else:
                df2.loc[index, "market_cumu"] = None

In [11]:
pd.set_option('display.max_columns', 100)
df2

,Date,Open,Delta,FractionalIncrease,High,Low,Positive,StockScore,reuter_score,reuter_credibility,reuter_cumu,fool_score,fool_credibility,fool_cumu,invest_score,invest_credibility,invest_cumu,cnbc_score,cnbc_credibility,cnbc_cumu,market_score,market_credibility,market_cumu
0,2016-11-17,83.270,0.510,0.006162,84.764,81.232,True,0.030623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-11-25,83.530,0.260,0.003122,84.040,81.720,True,0.015563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-12-01,84.754,1.224,0.014653,84.956,81.959,True,0.072209,-0.557100,0.963896,0.963896,0.997000,0.963896,0.963896,NaN,NaN,NaN,0.945100,0.963896,0.963896,NaN,NaN,NaN
3,2016-12-08,84.821,0.067,0.000791,85.255,83.424,True,0.003949,0.928700,0.998025,0.980960,NaN,NaN,0.963896,NaN,NaN,NaN,0.908833,0.998025,0.980960,0.988333,0.998025,0.998025
4,2016-12-15,86.797,1.976,0.023296,89.797,84.436,True,0.113829,0.928700,0.943086,0.962023,NaN,NaN,0.963896,0.9985,0.943086,0.943086,0.864750,0.943086,0.962023,0.997800,0.943086,0.970555
5,2016-12-22,86.719,-0.078,-0.000899,88.308,86.469,False,-0.004497,NaN,NaN,0.962023,NaN,NaN,0.963896,NaN,NaN,0.943086,0.999800,0.997751,0.979887,0.973900,0.997751,0.984153
6,2016-12-29,86.797,0.078,0.000899,87.768,86.719,True,0.004493,0.961200,0.997753,0.979888,NaN,NaN,0.963896,NaN,NaN,0.943086,0.984000,0.997753,0.988820,0.981400,0.997753,0.990953
7,2017-01-05,86.883,0.086,0.000991,87.990,86.459,True,0.004949,NaN,NaN,0.979888,0.998000,0.997525,0.980710,NaN,NaN,0.943086,0.991400,0.997525,0.993173,0.990600,0.997525,0.994239
8,2017-01-12,84.070,-2.813,-0.032377,86.989,82.712,False,-0.167301,0.685567,0.916349,0.948119,0.999150,0.916349,0.948530,NaN,NaN,0.943086,0.993000,0.916349,0.954761,0.934700,0.916349,0.955294
9,2017-01-19,82.818,-1.252,-0.014892,84.205,82.894,False,-0.075587,0.968900,0.962206,0.955163,0.993100,0.962206,0.955368,0.9169,0.962206,0.952646,0.988950,0.962206,0.958484,0.998500,0.962206,0.958750
10,2017-01-26,82.548,-0.270,-0.003260,82.943,81.489,False,-0.016354,0.982600,0.991823,0.973493,0.992400,0.991823,0.973596,NaN,NaN,0.952646,0.004450,0.991823,0.975153,-0.851800,0.991823,0.975287
11,2017-02-02,80.159,-2.389,-0.028941,82.682,79.513,False,-0.149016,0.967000,0.925492,0.949492,0.996350,0.925492,0.949544,NaN,NaN,0.952646,NaN,NaN,0.975153,0.994000,0.925492,0.950389
12,2017-02-09,79.521,-0.638,-0.007959,80.650,78.909,False,-0.040115,NaN,NaN,0.949492,0.994200,0.979942,0.964743,NaN,NaN,0.952646,NaN,NaN,0.975153,NaN,NaN,0.950389
13,2017-02-16,80.804,1.283,0.016134,80.867,79.389,True,0.079390,-0.790600,0.960305,0.954899,NaN,NaN,0.964743,NaN,NaN,0.952646,0.997100,0.960305,0.967729,0.995000,0.960305,0.955347
14,2017-02-23,79.151,-1.653,-0.020457,81.096,78.616,False,-0.104421,NaN,NaN,0.954899,0.998400,0.947790,0.956266,0.9972,0.947790,0.950218,0.997100,0.947790,0.957759,0.979825,0.947790,0.951568
15,2017-03-02,80.493,1.342,0.016955,81.008,78.510,True,0.083361,0.975300,0.958319,0.956609,0.998400,0.958319,0.957293,NaN,NaN,0.950218,0.999100,0.958319,0.958039,0.997600,0.958319,0.954944
16,2017-03-09,78.393,-2.100,-0.026089,81.903,78.753,False,-0.133941,0.732067,0.933030,0.944819,0.993450,0.933030,0.945161,0.9693,0.933030,0.941624,0.986100,0.933030,0.945535,0.997400,0.933030,0.943987
17,2017-03-16,79.745,1.352,0.017246,80.173,78.072,True,0.084770,-0.971600,0.957615,0.951217,0.992550,0.957615,0.951388,NaN,NaN,0.941624,0.994900,0.957615,0.951575,0.993600,0.957615,0.950801
18,2017-03-23,79.356,-0.389,-0.004878,80.056,79.161,False,-0.024510,0.020050,0.987745,0.969481,0.997200,0.987745,0.969567,0.9936,0.987745,0.964684,0.998600,0.987745,0.969660,0.202300,0.987745,0.969273
19,2017-03-30,79.745,0.389,0.004902,79.991,78.540,True,0.024390,0.875000,0.987805,0.978643,NaN,NaN,0.969567,0.9936,0.987805,0.976245,0.986650,0.987805,0.978732,NaN,NaN,0.969273
20,2017-04-06,80.445,0.700,0.008778,81.532,79.064,True,0.043508,0.992800,0.978246,0.978445,0.999500,0.978246,0.973906,NaN,NaN,0.976245,0.945100,0.978246,0.978489,0.998700,0.978246,0.973759
21,2017-04-13,80.415,-0.030,-0.000373,81.144,80.123,False,-0.001865,-0.995000,0.999067,0.988756,NaN,NaN,0.973906,NaN,NaN,0.976245,0.563600,0.999067,0.988778,-0.996100,0.999067,0.986413
22,2017-04-20,78.695,-1.720,-0.021389,80.424,78.063,False,-0.109283,-0.995000,0.945359,0.967057,0.996067,0.945359,0.959632,NaN,NaN,0.976245,0.994700,0.945359,0.967068,0.983600,0.945359,0.965886
23,2017-04-27,78.812,0.117,0.001487,80.036,78.228,True,0.007423,0.979400,0.996289,0.981673,0.993250,0.996289,0.977961,0.9973,0.996289,0.986267,0.991150,0.996289,0.981679,0.992500,0.996289,0.981087
24,2017-05-04,79.997,1.185,0.015036,80.756,78.685,True,0.074065,-0.918600,0.962967,0.972320,0.995200,0.962967,0.970464,NaN,NaN,0.986267,NaN,NaN,0.981679,0.944200,0.962967,0.972027
25,2017-05-11,81.047,1.050,0.013125,80.831,79.133,True,0.064777,0.947700,0.967611,0.969966,NaN,NaN,0.970464,NaN,NaN,0.986267,NaN,NaN,0.981679,NaN,NaN,0.972027
26,2017-05-18,80.242,-0.805,-0.009933,81.675,80.429,False,-0.050161,0.493900,0.974920,0.972443,NaN,NaN,0.970464,0.9983,0.974920,0.980593,-0.953800,0.974920,0.978299,0.998300,0.974920,0.973473
27,2017-05-25,80.792,0.550,0.006854,81.336,79.899,True,0.034038,NaN,NaN,0.972443,NaN,NaN,0.970464,NaN,NaN,0.980593,NaN,NaN,0.978299,NaN,NaN,0.973473
28,2017-06-01,78.868,-1.924,-0.023814,81.165,78.967,False,-0.121976,NaN,NaN,0.972443,NaN,NaN,0.970464,NaN,NaN,0.980593,NaN,NaN,0.978299,NaN,NaN,0.973473
29,2017-06-08,79.006,0.138,0.001750,79.880,77.779,True,0.008734,NaN,NaN,0.972443,0.997700,0.995633,0.983049,0.9856,0.995633,0.988113,NaN,NaN,0.978299,0.979600,0.995633,0.984553
30,2017-06-15,80.252,1.246,0.015771,82.127,78.986,True,0.077630,0.897150,0.961185,0.966814,0.994000,0.961185,0.972117,NaN,NaN,0.988113,0.994000,0.961185,0.969742,0.983600,0.961185,0.972869
31,2017-06-22,79.928,-0.324,-0.004037,81.979,79.624,False,-0.020268,NaN,NaN,0.966814,0.994000,0.989866,0.980991,0.9915,0.989866,0.988990,NaN,NaN,0.969742,0.987400,0.989866,0.981367
32,2017-06-29,79.850,-0.078,-0.000976,80.232,79.252,False,-0.004884,0.892650,0.997558,0.982186,0.994550,0.997558,0.989275,0.9915,0.997558,0.993274,0.831600,0.997558,0.983650,NaN,NaN,0.981367
33,2017-07-06,79.350,-0.500,-0.006262,80.949,78.908,False,-0.031506,0.918300,0.984247,0.983216,0.999800,0.984247,0.986761,NaN,NaN,0.993274,0.957400,0.984247,0.983948,0.991800,0.984247,0.982807
34,2017-07-13,79.458,0.108,0.001361,79.992,78.319,True,0.006796,0.895700,0.996602,0.989909,0.999000,0.996602,0.991681,NaN,NaN,0.993274,0.983200,0.996602,0.990275,0.999700,0.996602,0.989705
35,2017-07-20,79.458,0.000,0.000000,79.908,78.770,True,0.000000,0.895700,1.000000,0.994955,0.996800,1.000000,0.995841,0.9916,1.000000,0.996637,0.994900,1.000000,0.995138,0.947700,1.000000,0.994852
36,2017-07-27,78.741,-0.717,-0.009024,79.968,78.270,False,-0.045529,-0.982100,0.977235,0.986095,NaN,NaN,0.995841,0.8860,0.977235,0.986936,NaN,NaN,0.995138,0.918700,0.977235,0.986044
37,2017-08-03,78.839,0.098,0.001245,79.369,76.808,True,0.006215,-0.982100,0.996892,0.991494,NaN,NaN,0.995841,0.9962,0.996892,0.991914,NaN,NaN,0.995138,NaN,NaN,0.986044
38,2017-08-10,79.029,0.190,0.002410,79.310,78.289,True,0.012021,0.989200,0.993990,0.992742,NaN,NaN,0.995841,NaN,NaN,0.991914,-0.526700,0.993990,0.994564,NaN,NaN,0.986044
39,2017-08-17,76.552,-2.477,-0.031343,79.048,76.601,False,-0.161785,-0.700300,0.919107,0.955924,0.996800,0.919107,0.957474,NaN,NaN,0.991914,0.205200,0.919107,0.956835,0.077200,0.919107,0.952576
40,2017-08-24,75.798,-0.754,-0.009850,76.626,75.353,False,-0.049737,NaN,NaN,0.955924,0.981150,0.975131,0.966303,NaN,NaN,0.991914,0.999050,0.975131,0.965983,0.996300,0.975131,0.963853
41,2017-08-31,75.571,-0.227,-0.002995,76.423,75.363,False,-0.015019,NaN,NaN,0.955924,NaN,NaN,0.966303,NaN,NaN,0.991914,NaN,NaN,0.965983,NaN,NaN,0.963853
42,2017-09-07,78.295,2.724,0.036046,78.499,75.353,True,0.173957,NaN,NaN,0.955924,NaN,NaN,0.966303,NaN,NaN,0.991914,NaN,NaN,0.965983,NaN,NaN,0.963853
43,2017-09-14,79.118,0.823,0.010512,79.039,77.889,True,0.052011,NaN,NaN,0.955924,NaN,NaN,0.966303,NaN,NaN,0.991914,NaN,NaN,0.965983,NaN,NaN,0.963853
44,2017-09-21,79.752,0.634,0.008013,79.920,78.821,True,0.039748,-0.868900,0.980126,0.968025,0.996700,0.980126,0.973214,0.9243,0.980126,0.986020,0.296000,0.980126,0.973055,0.996500,0.980126,0.971990
45,2017-09-28,80.881,1.129,0.014156,80.703,78.939,True,0.069794,-0.690800,0.965103,0.966564,0.996200,0.965103,0.969159,NaN,NaN,0.986020,-0.882400,0.965103,0.969079,-0.057000,0.965103,0.968546
46,2017-10-05,80.971,0.090,0.001113,81.694,80.500,True,0.005558,NaN,NaN,0.966564,NaN,NaN,0.969159,NaN,NaN,0.986020,NaN,NaN,0.969079,NaN,NaN,0.968546
47,2017-10-12,81.555,0.584,0.007212,81.981,80.609,True,0.035804,NaN,NaN,0.966564,NaN,NaN,0.969159,NaN,NaN,0.986020,NaN,NaN,0.969079,NaN,NaN,0.968546
48,2017-10-19,81.595,0.040,0.000490,82.626,81.417,True,0.002451,NaN,NaN,0.966564,0.997800,0.998774,0.983967,NaN,NaN,0.986020,0.645900,0.998774,0.983927,0.995200,0.998774,0.983660
49,2017-10-26,82.606,1.011,0.012390,83.038,81.575,True,0.061194,NaN,NaN,0.966564,0.084450,0.969403,0.976685,0.9911,0.969403,0.977712,0.148000,0.969403,0.976665,0.997000,0.969403,0.976532
50,2017-11-02,82.833,0.227,0.002748,83.468,81.258,True,0.013702,-0.998500,0.993149,0.979856,NaN,NaN,0.976685,0.9913,0.993149,0.985430,0.991500,0.993149,0.984907,0.993300,0.993149,0.984840
51,2017-11-09,82.536,-0.297,-0.003586,83.101,82.100,False,-0.017992,NaN,NaN,0.979856,NaN,NaN,0.976685,NaN,NaN,0.985430,NaN,NaN,0.984907,NaN,NaN,0.984840

In [12]:
df2.to_csv("../scoredSelected/exxonscored.csv", index = False)
# df2.loc[(df2["reuter_count"] > 0) & (df2["fool_count"] > 0) & (df2["invest_count"] > 0) & (df2["cnbc_count"] > 0) & (df2["market_count"] > 0)]